config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show]

  resource :cart, only: [:show, :destroy] do
    collection do
      post :add, path:'add/:id'
      get :checkout
    end
  end

  resources :orders, only: [:create] do
    member do
      delete :cancel
    end
  end

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def serialize
    item_list = items.map { |item|
      { "product_id" => item.product_id, "quantity" => item.quantity }
    }

    { "items" => item_list }
  end

  def self.from_hash(hash)
    all_items = []
    if hash && hash["items"]
      all_items = hash["items"].map { |item|
        CartItem.new(item["product_id"], item["quantity"])
      }
    end

    new(all_items)
  end

  def add_item(id)
    found_item = @items.find { |item| item.product_id == id }

    if found_item
      found_item.increment
    else
      @items << CartItem.new(id)
    end
  end

  def empty?
    @items.empty?
  end

  def total_price
    total = items.reduce(0) { |sum, item| sum + item.total_price }

    case
    when xmas?
      total * 0.9
    else
      total
    end
  end

  private
  def xmas?
    Time.now.month == 12 && Time.now.day == 25
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize(product_id, quantity = 1)
    @product_id = product_id
    @quantity = quantity
  end

  def increment(n = 1)
    @quantity += n
  end

  def product
    Product.find_by(id: product_id)
  end

  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  include AASM

  aasm column: :state do
    state :pending, :initial => true
    state :paid, :shipped, :delivered, :refunded

    event :pay do
      transitions :from => :pending, :to => :paid
    end

    event :ship do
      transitions :from => :paid, :to => :shipped
      after_commit do
        puts "發送簡訊!"
      end
    end

    event :deliver do
      transitions :from => :shipped, :to => :delivered
    end

    event :refund do
      transitions :from => [:delivered, :paid], :to => :refunded
    end
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include CartsHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add
    current_cart.add_item(params[:id])
    session[:cart9527] = current_cart.serialize

    redirect_to products_path, notice: "商品已加入購物車!"
  end

  def show
  end

  def checkout
    @order = Order.new
  end

  def destroy
    session[:cart9527] = nil
    redirect_to products_path, notice: "購物車已清空!"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    # 建立訂單
    order = Order.new(order_params)

    current_cart.items.each do |item|
      order.order_items.build(
        product: item.product,
        quantity: item.quantity
      )
    end

    if order.save
      # 刷卡
      result = Braintree::Transaction.sale(
        :amount => current_cart.total_price,
        :payment_method_nonce => params[:payment_method_nonce]
      )

      if result.success?
        # 通知信
        OrderMailer.hello(order_params[:email]).deliver_later

        # 清空 Cart
        session[:cart9527] = nil
        # 走
        redirect_to products_path, notice: "感謝消費!"
      else
        # ...
      end
    else
      # ...
    end
  end

  private
  def order_params
    params.require(:order).permit(
      :receipent,
      :tel,
      :address,
      :email
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    OrderMailer.hello("eddie@5xruby.tw").deliver_later
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :available)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    @cart ||= Cart.from_hash(session[:cart9527])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<table>
  <tr>
    <td>品名</td>
    <td>數量</td>
    <td>單價</td>
    <td>小計</td>
  </tr>
  <% current_cart.items.each do |item| %>
  <tr>
    <td><%= item.product.title %></td>
    <td><%= item.quantity %></td>
    <td><%= item.product.price %></td>
    <td><%= item.total_price %></td>
  </tr>
  <% end %>
  <tr>
    <td colspan="4">
      總計：<%= current_cart.total_price %>
    </td>
  </tr>
</table>

app/views/carts/checkout.html.erb
<h1>結帳</h1>

<%= render "cart" %>

<%= simple_form_for @order do |f| %>
  <%= f.input :receipent %>
  <%= f.input :tel %>
  <%= f.input :address %>
  <%= f.input :email %>
  <hr />
  <div id="payment-form"></div>
  <hr />
  <%= f.submit "確認送出" %>
<% end %>

<script src="https://js.braintreegateway.com/js/braintree-2.32.1.min.js"></script>
<script>
var clientToken = "<%= Braintree::ClientToken.generate %>";

braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});
</script>

app/views/carts/show.html.erb
<h1>檢視購物車</h1>

<%= render "cart" %>

<%= link_to "繼續選購", products_path %>
<%= link_to "結帳", checkout_cart_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyShoppingMall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    購物車：<%= current_cart.items.count %>
    <% unless current_cart.empty? %>
      <%= link_to "檢視", cart_path %>
      <%= link_to "清空", cart_path, method: "delete" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available, id: :product_available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= link_to "放入購物車", add_cart_path(product), method: "post" %>
          <%= link_to product.title, product %>
        </td>
        <td><%= product.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<%= link_to 'Back', products_path %>